### ISSUE TITLE
tripaldock new exiting 

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripaldock#46]
```

Creating docked_elasticsearch_1 ... done
Creating docked_postgres_1      ... done
Creating docked_app_1           ... done
 5/9 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░]  55%

 TRIPALDOCK: Installing Drupal
You are about to create a /var/www/html/sites/default/settings.php file and DROP all tables in your 'docked' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the [ok]
--notify global option.
Exception: Resolve all issues below to continue the installation. For[error]
help configuring your database server, see the <a
href="http://drupal.org/getting-started/install">installation
handbook</a>, or contact your hosting provider.<p
class="error">Failed to connect to your database server. The server
reports the following message: <em>SQLSTATE[08006] [7] could not
connect to server: Connection refused
	Is the server running on host &quot;postgres&quot; (192.168.32.3)
and accepting
	TCP/IP connections on port 5432?</em>.<ul><li>Is the database server
running?</li><li>Does the database exist, and have you entered the
correct database name?</li><li>Have you entered the correct username
and password?</li><li>Have you entered the correct database
hostname?</li></ul></p> in
/var/www/html/includes/install.core.inc:415
Stack trace:
#0 /var/www/html/includes/install.core.inc(339):
install_run_task(Array, Array)
#1 /var/www/html/includes/install.core.inc(77):
install_run_tasks(Array)
#2 /root/.composer/vendor/drush/drush/includes/drush.inc(723):
install_drupal(Array)
#3 /root/.composer/vendor/drush/drush/includes/drush.inc(709):
drush_call_user_func_array('install_drupal', Array)
#4
/root/.composer/vendor/drush/drush/commands/core/drupal/site_install_7.inc(82):
drush_op('install_drupal', Array)
#5
/root/.composer/vendor/drush/drush/commands/core/site_install.drush.inc(291):
drush_core_site_install_version('standard', Array)
#6 /root/.composer/vendor/drush/drush/includes/command.inc(361):
drush_core_site_install('standard', 'install_configu...')
#7 /root/.composer/vendor/drush/drush/includes/command.inc(212):
_drush_invoke_hooks(Array, Array)
#8 /root/.composer/vendor/drush/drush/includes/command.inc(180):
drush_command('standard', 'install_configu...')
#9
/root/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(64):
drush_dispatch(Array)
#10 /root/.composer/vendor/drush/drush/drush.php(70):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#11 /root/.composer/vendor/drush/drush/drush.php(11): drush_main()
#12 {main}

In NewCommand.php line 561:

  Exited with code 1


new <name>

```

**Comment by almasaeed2010** [comment]
That's because you have a database already running on port `5432`. It's supposed to detect that though and assign a new port. Can you verify you are running the latest tripaldock?

```
composer global update tripaldock
```

**Comment by bradfordcondon** [comment]
oops i was on 0.0.9  i updated but updated my local, not global verson.  then i ran tripaldock up with global sorry
